### ISSUE TITLE
Make compatible with latest stable version of factorio

### ISSUE THREAD

**Issue by rik-rosseel** [raiguard/ChangeInserterDropLane#1]
I'm not sure if there is a specific reason to not do this? If there isn't then I feel like it would be good to support the latest stable version of the game.

![image](https://user-images.githubusercontent.com/36194842/224355378-e827d5aa-4696-476a-a7ab-a89b6dd753f2.png)
![image](https://user-images.githubusercontent.com/36194842/224356001-50bcd87b-dfb5-4d94-bb9e-d42eacd8dc4f.png)

**Comment by raiguard** [comment]
See my comment on #2
