### ISSUE TITLE
Unintended feature? Copy paste long inserter.

### ISSUE THREAD

**Issue by gaoguibarnez** [raiguard/ChangeInserterDropLane#3]
### Description

It is possible to use the copy paste feature (shift + right click then shift + left click) to turn any inserter into a long inserter. Copying a normal inserter into a long inserter also makes the long inserter work as a normal inserter.

### Reproduction

Build long inserter and any normal inserter.
Copy (shift + right click) long inserter and paste to normal inserter (shift + left click).
Normal inserter now works as long inserter.

**Comment by raiguard** [comment]
Lol, oops.

**Comment by raiguard** [comment]
Fixed in b0e6765
