### ISSUE TITLE
Can't change the lane the inserter drops to when dropping to a backwards underground belt

### ISSUE THREAD

**Issue by Papweer** [raiguard/ChangeInserterDropLane#6]
### Description

When you try to change the lane an inserter is dropping to when dropping to an underground belt facing the inserter nothing happens.
![image](https://github.com/raiguard/ChangeInserterDropLane/assets/158085165/fd0fe2ce-cba3-4304-b11a-ecab22f98dd3)

**Comment by raiguard** [comment]
This isn't easily fixed, see https://github.com/raiguard/Krastorio2/issues/329.
